[build.environment]
  GCAL_CLIENT_ID="4436581685-mcdkhnh50a6di21k15do7d4a2orq7faf.apps.googleusercontent.com"
  GCAL_API_KEY="AIzaSyCssknAiVBtWhHE3O1wjVte829dxoxQ-pM"

[context.production.environment]
  GCAL_CLIENT_ID="4436581685-mcdkhnh50a6di21k15do7d4a2orq7faf.apps.googleusercontent.com"
  GCAL_API_KEY="AIzaSyCssknAiVBtWhHE3O1wjVte829dxoxQ-pM"
