// Search
export const FETCH_SEARCH_RESULTS_REQUEST = 'FETCH_SEARCH_RESULTS_REQUEST';
export const FETCH_SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS';
export const FETCH_SEARCH_RESULTS_FAILURE = 'SEARCH_RESULTS_FAILURE';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const FETCH_SECTIONS_FOR_SEARCH_REQUEST = 'FETCH_SECTIONS_FOR_SEARCH_REQUEST';
export const FETCH_SECTIONS_FOR_SEARCH_SUCCESS = 'FETCH_SECTIONS_FOR_SEARCH_SUCCESS';
export const FETCH_SECTIONS_FOR_SEARCH_FAILURE = 'FETCH_SECTIONS_FOR_SEARCH_FAILURE';
export const SET_CURRENT_COURSE_NAME = 'SET_CURRENT_COURSE_NAME';
export const VIEW_SEARCH = 'VIEW_SEARCH';
export const VIEW_SECTION_SELECTION = 'VIEW_SECTION_SELECTION';
export const UPDATE_SEARCH_INPUT = 'UPDATE_SEARCH_INPUT';
export const ADD_SECTION_FROM_SEARCH = 'ADD_SECTION_FROM_SEARCH';
export const ADD_SECTION_WITH_ASSOCIATED_CLASS_FROM_SEARCH = 'ADD_SECTION_WITH_ASSOCIATED_CLASS_FROM_SEARCH';

// Browse
export const FETCH_SCHOOLS_REQUEST = 'FETCH_SCHOOLS_REQUEST';
export const FETCH_SCHOOLS_SUCCESS = 'FETCH_SCHOOLS_SUCCESS';
export const FETCH_SCHOOLS_FAILURE = 'FETCH_SCHOOLS_FAILURE';
export const FETCH_SUBJECTS_REQUEST = 'FETCH_SUBJECTS_REQUEST';
export const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS';
export const FETCH_SUBJECTS_FAILURE = 'FETCH_SUBJECTS_FAILURE';
export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';
export const FETCH_SECTIONS_FOR_BROWSE_REQUEST = 'FETCH_SECTIONS_FOR_BROWSE_REQUEST';
export const FETCH_SECTIONS_FOR_BROWSE_SUCCESS = 'FETCH_SECTIONS_FOR_BROWSE_SUCCESS';
export const FETCH_SECTIONS_FOR_BROWSE_FAILURE = 'FETCH_SECTIONS_FOR_BROWSE_FAILURE';
export const CHANGE_BROWSE_LEVEL = 'CHANGE_BROWSE_LEVEL';
export const SELECT_SCHOOL_IN_BROWSE = 'SELECT_SCHOOL_IN_BROWSE';
export const SELECT_SUBJECT_IN_BROWSE = 'SELECT_SUBJECT_IN_BROWSE';
export const SELECT_COURSE_IN_BROWSE = 'SELECT_COURSE_IN_BROWSE';
export const ADD_SECTION_FROM_BROWSE = 'ADD_SECTION_FROM_BROWSE';
export const ADD_SECTION_WITH_ASSOCIATED_CLASS_FROM_BROWSE = 'ADD_SECTION_WITH_ASSOCIATED_CLASS_FROM_BROWSE';

// Schedule
export const REMOVE_SECTION = 'REMOVE_SECTION';
export const REMOVE_ALL_CLASSES = 'REMOVE_ALL_CLASSES';
export const SECTION_HOVER = 'SECTION_HOVER';
export const SECTION_HOVER_OFF = 'SECTION_HOVER_OFF';
export const ASSOCIATED_CLASS_HOVER = 'ASSOCIATED_CLASS_HOVER';
export const ASSOCIATED_CLASS_HOVER_OFF = 'ASSOCIATED_CLASS_HOVER_OFF';
